## 00. Pytorch Fundamentals

See https://www.learnpytorch.io/00_pytorch_fundamentals/

In [9]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.tensor()` - https://pytorch.org/docs/stable/tensors.html

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
# Create a random tesnor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6975, 0.3290, 0.1068, 0.2600],
        [0.6183, 0.4948, 0.0734, 0.3331],
        [0.0468, 0.3513, 0.3537, 0.2886]])

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [37]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not on right datatype
2. Tensors not right shape
3. Tensors not on right device

In [45]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,              # what datatype is the tensor (eg. float16, float32), default is float32
                               device=None,             # what device is your tensor on, default is "cpu", other is "cuda"
                               requires_grad=False)     # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_32_tensor.dtype

torch.float32

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [49]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [50]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not on right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.size`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`


In [52]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8381, 0.3114, 0.8411, 0.0923],
        [0.2069, 0.7905, 0.3826, 0.0791],
        [0.9610, 0.5551, 0.0483, 0.2901]])

In [54]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8381, 0.3114, 0.8411, 0.0923],
        [0.2069, 0.7905, 0.3826, 0.0791],
        [0.9610, 0.5551, 0.0483, 0.2901]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [56]:
some_gpu_tensor = some_tensor.to(device="cuda")
some_gpu_tensor

tensor([[0.8381, 0.3114, 0.8411, 0.0923],
        [0.2069, 0.7905, 0.3826, 0.0791],
        [0.9610, 0.5551, 0.0483, 0.2901]], device='cuda:0')

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [57]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [58]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [59]:
tensor

tensor([1, 2, 3])

In [60]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [61]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [62]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work 
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [63]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [64]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [69]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

# torch.mm(tensor_A, tensor_B)   # torch.mm is the same as torch.matmul (it's an alias for less writing)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [70]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors isong a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [72]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [75]:
# The matric multiplication operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [84]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [85]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [86]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [87]:
# Find the mean - x is of type int64 so must be converted to float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [88]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [90]:
# Find the position in tensor that has the minmum value -> resturns index position
x.argmin()

tensor(0)

In [91]:
# Find the position in tensor that has the maximum value -> returns index position
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [9]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [11]:
# Change the view - similar to reshape but shares the same memory as x
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [16]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [42]:
# torch.squeeze() - removes all single dimensions
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()

In [43]:
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_squeezed, x_squeezed.shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
# Add extra dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

In [45]:
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))   # [height, width, colour_channels]


In [49]:
x_original.shape

torch.Size([224, 224, 3])

In [50]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # shifts axis 0->1, 1->2, 2->0

In [51]:
x_permuted.shape

torch.Size([3, 224, 224])

In [53]:
x_original[0, 0, 0] = 10.01

In [55]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(10.0100), tensor(10.0100))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [56]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# Index on our new tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
# index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [59]:
# Index on the most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [63]:
# You can also use ":" to slect "all" of a target dimension. Note this requires the alternative format x[0, 0, 0].
x[:, 0]

tensor([[1, 2, 3]])

In [64]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [65]:
# Get all values of the 0 dimension but only 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [69]:
# Get index 0 0f 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## Pytorch tensors and NumPy

PyTorch has functionality to interect with NumPy.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [72]:
# NumPy array to tensor
import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)    # Note: default type is float64 to match NumPy
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
# Change the value of array, what will this so to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()   # leaves dtype at float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...

To reduce the randomness in neural networks and PyTorch comes hte concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [5]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3674, 0.7150, 0.8958, 0.6808],
        [0.4934, 0.4965, 0.5592, 0.6950],
        [0.9024, 0.0059, 0.9226, 0.1331]])
tensor([[0.4038, 0.8569, 0.4907, 0.1998],
        [0.8188, 0.0081, 0.6386, 0.2905],
        [0.9243, 0.8818, 0.1940, 0.6354]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [7]:
# Let's make some random but reproducible tensors
import torch

# Set random seed - needs to be set for each call to rand
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)

In [1]:
# Check for GPU access with PyTorch
import torch
print(torch.cuda.is_available())

True


For Pytorch since it's capabale of running compute on the GPU or CPU, it's best pratice to setup dice agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html

eg. run on GPU id available, else default to CPU

In [2]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [3]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [4]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

In [5]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU (eg. for NumPy)

In [6]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])